spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/automation_sut
    username: sut_user
    password: sut_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
